// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAiysIBjDpd6X5P-k4V1i9xmXXY2Ld5s0',
    appId: '1:550903779760:android:0a1b97d404800faf608675',
    messagingSenderId: '550903779760',
    projectId: 'babybook-efc90',
    storageBucket: 'babybook-efc90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBha-fyxBIBnoC1KLgN0u9FSZE-HO1AJJE',
    appId: '1:550903779760:ios:44794a4c3c6c77c3608675',
    messagingSenderId: '550903779760',
    projectId: 'babybook-efc90',
    storageBucket: 'babybook-efc90.appspot.com',
    iosBundleId: 'com.example.babyBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBha-fyxBIBnoC1KLgN0u9FSZE-HO1AJJE',
    appId: '1:550903779760:ios:44794a4c3c6c77c3608675',
    messagingSenderId: '550903779760',
    projectId: 'babybook-efc90',
    storageBucket: 'babybook-efc90.appspot.com',
    iosBundleId: 'com.example.babyBook',
  );
}
